### ISSUE TITLE
XML format  converted to NIFTI files

### ISSUE THREAD

**Issue by chengjianhong** [svaishnavi411/multimodal-recurrence#1]
Hi,
  Can you tell me how to convert the segmentation from XML format to NIFTI files?
Regards,
Jianhong

**Comment by svaishnavi411** [comment]
Hi Jianhong,

I made use of the converter from dcmqi: Converters between research formats and DICOM (http://qiicr.org/tool/dcmqi/)

Regards,
Vaishnavi

**Comment by chengjianhong** [comment]
Is there a simple example code here? Thanks.

**Comment by chengjianhong** [comment]
> Hi Jianhong,
> 
> I made use of the converter from dcmqi: Converters between research formats and DICOM (http://qiicr.org/tool/dcmqi/)
> 
> Regards,
> Vaishnavi


Hi @svaishnavi411,
Is there a simple example code here? Thanks.

**Comment by svaishnavi411** [comment]
@chengjianhong 

I don't have the exact code I used. However, here is a link to the tutorial I made use of: http://qiicr.org/dcmqi-guide/tutorials/intro.html. Further, the segmentations used in this work are available for download from https://uofi.box.com/v/nsclc-radiogenomics-curated

**Comment by Lumemgyi** [comment]
@svaishnavi411 Hi, I found the ROI segmentation sequence compression file of CT image in your link, so do you have the ROI segmentation compression file of pet/ct part in NSCLC radiogenomic database?

**Comment by svaishnavi411** [comment]
Hi @Lumemgyi 
I did not use PET/CT scans in my analysis, and therefore did not process the related segmentation files. You can find the available XML annotations in the original NSCLC dataset (https://wiki.cancerimagingarchive.net/display/Public/NSCLC+Radiogenomics). You can convert these (http://qiicr.org/dcmqi-guide/tutorials/intro.html).

**Comment by Lumemgyi** [comment]
Hi again @svaishnavi411 
I will try to do it with your advice. thanks
regards
Lumemgyi
