### ISSUE TITLE
Genomic file is not found

### ISSUE THREAD

**Issue by hamimughal** [svaishnavi411/multimodal-recurrence#3]
hey, I am doing study on the work and make is as a base paper, I have find all data and code but one file is not found "genomics_cleaned.csv" so my working is stopped so please ensure about this file. I am waiting your respace.
Thank you.

**Comment by svaishnavi411** [comment]
Thank you for your interest in our work. I just uploaded it to the Box data link. Let me know if you need anything else.

**Comment by hamimughal** [comment]
Thank you so much for your response. I'll be waiting for that file.
Thank you.

**Comment by svaishnavi411** [comment]
The file is available here: https://uofi.box.com/v/nsclc-radiogenomics-curated
